package main

import (
	"encoding/json"
	"fmt"
	"bytes"
)

type AutoGenerated struct {
	Graphs struct {
		Superdice struct {
			Label   string `json:"label"`
			Unit    string `json:"unit"`
			Metrics []struct {
				Name  string `json:"name"`
				Label string `json:"label"`
			} `json:"metrics"`
		} `json:"superdice"`
	} `json:"graphs"`
}

func main() {

	jsonStr := `
{
     "graphs":{
     "superdice": {
        "label": "My Dice",
        "unit": "integer",
     "metrics":[
       {
         "name":"d6",
        "label":"Die"
       },
       {
        "name":"d20",
        "label":"Die (d20)"
       }
     ]
   }
  }
}
`

	jsonBytes, err := json.Marshal(jsonStr)
	if err != nil {
		fmt.Println("JSON Marshal error:", err)
		return
	}

	out := new(bytes.Buffer)
	json.Indent(out, jsonBytes, "", "    ")
	fmt.Println(out.String())
}
